# Generated by Django 5.2 on 2025-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_feedback_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_leave_balance',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='sick_leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacation_leave_balance',
            field=models.IntegerField(default=5),
        ),
    ]
