# Generated by Django 5.1.7 on 2025-04-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_event_time_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
