# Generated by Django 5.1.7 on 2025-04-14 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('dob', models.DateField(default='1900-01-01')),
                ('mobile_number', models.CharField(default='Not provided', max_length=15)),
                ('address', models.CharField(default='No address provided', max_length=255)),
                ('father_name', models.CharField(default='Unknown', max_length=255)),
                ('mother_name', models.CharField(default='Unknown', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
